package lfp.proyecto2;

import Lexico.Analizador;
import Reportes.Reporte;
import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author libni
 */
public class Formulario extends javax.swing.JFrame {

   JFileChooser seleccionar = new JFileChooser();
   File archivo;
   FileInputStream entrada;
   FileOutputStream salida;
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        this.setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ABRIR = new javax.swing.JMenuItem();
        GUARDAR = new javax.swing.JMenuItem();
        GUARDARC = new javax.swing.JMenuItem();
        SALIR = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ANALISIS = new javax.swing.JMenuItem();
        SINTACTICO = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        REPORTETKN = new javax.swing.JMenuItem();
        REPORTES = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ACERCA = new javax.swing.JMenuItem();
        TECNICO = new javax.swing.JMenuItem();
        USUARIO = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(texto);

        jMenu1.setText("Archivo");

        ABRIR.setText("Abrir");
        ABRIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABRIRActionPerformed(evt);
            }
        });
        jMenu1.add(ABRIR);

        GUARDAR.setText("Guardar");
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });
        jMenu1.add(GUARDAR);

        GUARDARC.setText("Guardar como");
        GUARDARC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARCActionPerformed(evt);
            }
        });
        jMenu1.add(GUARDARC);

        SALIR.setText("Salir");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        jMenu1.add(SALIR);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ejecutar");

        ANALISIS.setText("Analisis lexico");
        ANALISIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANALISISActionPerformed(evt);
            }
        });
        jMenu2.add(ANALISIS);

        SINTACTICO.setText("Analisis Sintactico");
        SINTACTICO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SINTACTICOActionPerformed(evt);
            }
        });
        jMenu2.add(SINTACTICO);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");

        REPORTETKN.setText("Reporte de simbolos");
        REPORTETKN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTETKNActionPerformed(evt);
            }
        });
        jMenu3.add(REPORTETKN);

        REPORTES.setText("Reporte de errores");
        REPORTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTESActionPerformed(evt);
            }
        });
        jMenu3.add(REPORTES);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");

        ACERCA.setText("Acerca de...");
        ACERCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACERCAActionPerformed(evt);
            }
        });
        jMenu4.add(ACERCA);

        TECNICO.setText("Manual tecnico");
        TECNICO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TECNICOActionPerformed(evt);
            }
        });
        jMenu4.add(TECNICO);

        USUARIO.setText("Manual de usuario");
        USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USUARIOActionPerformed(evt);
            }
        });
        jMenu4.add(USUARIO);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ABRIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABRIRActionPerformed
        // TODO add your handling code here:
        if(seleccionar.showDialog(null,"Abrir") == JFileChooser.APPROVE_OPTION)
        {
            archivo = seleccionar.getSelectedFile();
            if(archivo.canRead())
            {
                if(archivo.getName().endsWith("gss"))
                {                    
                    String documento = Abrir(archivo);
                    texto.setText(documento);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Archivo No Compatible");                    
                }
            }
        }
    }//GEN-LAST:event_ABRIRActionPerformed

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
        // TODO add your handling code here:
        if(seleccionar.showDialog(null,"Guardar")== JFileChooser.APPROVE_OPTION)
        {
            archivo = seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("gss"))
            {
                String Documento = texto.getText();
                String mensaje = GuardarA(archivo,Documento);
                if(mensaje !=null)
                {
                    JOptionPane.showMessageDialog(null,mensaje);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Archivo no Compatible");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Guardar Documento de Texto");
            }
        }
    }//GEN-LAST:event_GUARDARActionPerformed

    private void GUARDARCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARCActionPerformed
        // TODO add your handling code here:
        if(seleccionar.showDialog(null,"Guardar Como")== JFileChooser.APPROVE_OPTION)
        {
            archivo = seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("gss"))
            {
                String Documento = texto.getText();
                String mensaje = Guardar(archivo,Documento);
                if(mensaje !=null)
                {
                    JOptionPane.showMessageDialog(null,mensaje);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Archivo no Compatible");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Guardar Documento de Texto");
            }
        }
    }//GEN-LAST:event_GUARDARCActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"¿Desea salir de la aplicación?") == JOptionPane.OK_OPTION)
        {
         System.exit(0);   
        }
        else
        {
          
        } 
    }//GEN-LAST:event_SALIRActionPerformed

    private void ANALISISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANALISISActionPerformed
        // TODO add your handling code here:
      Analizador scanner = new Analizador();
      scanner.Scanner(texto.getText());
    }//GEN-LAST:event_ANALISISActionPerformed

    private void REPORTETKNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTETKNActionPerformed
        // TODO add your handling code here:
      Reporte visualizar = new Reporte();
      visualizar.Abrir();
    }//GEN-LAST:event_REPORTETKNActionPerformed

    private void REPORTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTESActionPerformed
        // TODO add your handling code here:
      Reporte visualizar = new Reporte();
      visualizar.EAbrir();
    }//GEN-LAST:event_REPORTESActionPerformed

    private void ACERCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACERCAActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"LFP PRACTICA\n Uzzi Libni Aarón Pineda Solórzano \n carné: 201403541");
    }//GEN-LAST:event_ACERCAActionPerformed

    private void TECNICOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TECNICOActionPerformed
        // TODO add your handling code here:
      try
        {
            File f = new File("E:/Lenguajes/Vacaciones/[LFP]Proyecto1_201403541/Manual Técnico.pdf");
            Desktop.getDesktop().open(f);
        }
        catch(IOException e)
        {
            e.printStackTrace();;
        }
        catch(IllegalArgumentException e)
        {
            JOptionPane.showMessageDialog(null, "Archivo no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_TECNICOActionPerformed

    private void USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USUARIOActionPerformed
        // TODO add your handling code here:
     try
     {
         File f = new File("E:/Lenguajes/Vacaciones/[LFP]Proyecto1_201403541/Manual de Usuario.pdf");
         Desktop.getDesktop().open(f);
     }
     catch(IOException e)
     {
         e.printStackTrace();;
     }
     catch(IllegalArgumentException e)
     {
         JOptionPane.showMessageDialog(null, "Archivo no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
         e.printStackTrace();
     }
    }//GEN-LAST:event_USUARIOActionPerformed

    private void SINTACTICOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SINTACTICOActionPerformed
        // TODO add your handling code here:          
        Interfaz frm = new Interfaz();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SINTACTICOActionPerformed

    public String Abrir(File archivo)
    {
        String documento="";
        try
        {
            entrada = new FileInputStream(archivo);
         int ascci;
         while((ascci = entrada.read()) !=-1)
         {
             char caracter =(char)ascci;
             documento +=caracter;
         }
        }catch(Exception e)
        {
            
        }  
        return documento;
    }
    
    public String Guardar(File archivo,String documento)
    {
        String mensaje = null;
        try
        {
         salida = new FileOutputStream(archivo);
         byte[] bytxt = documento.getBytes();
         salida.write(bytxt);
         mensaje="Archivo Guardado";
        }catch(Exception e)
        {
            
        }
        return mensaje;
    }
    
    public String GuardarA(File archivo,String documento)
    {
        String mensaje = null;
        try
        {
         salida = new FileOutputStream(archivo);
         byte[] bytxt = documento.getBytes();
         salida.write(bytxt);
         mensaje="Archivo Guardado";
        }catch(Exception e)
        {
            
        }
        return mensaje;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });              
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ABRIR;
    private javax.swing.JMenuItem ACERCA;
    private javax.swing.JMenuItem ANALISIS;
    private javax.swing.JMenuItem GUARDAR;
    private javax.swing.JMenuItem GUARDARC;
    private javax.swing.JMenuItem REPORTES;
    private javax.swing.JMenuItem REPORTETKN;
    private javax.swing.JMenuItem SALIR;
    private javax.swing.JMenuItem SINTACTICO;
    private javax.swing.JMenuItem TECNICO;
    private javax.swing.JMenuItem USUARIO;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane texto;
    // End of variables declaration//GEN-END:variables
}
