/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.*;
import AnalizadorLexico.Token;
import ListasPractica.ListaTkn;
import Reporte.HTML;
import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author libni
 */
public class Interfaz extends javax.swing.JFrame {
JFileChooser seleccionar = new JFileChooser();
        File archivo;
        FileInputStream entrada;
        FileOutputStream salida;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        ARCHIVO = new javax.swing.JMenu();
        ABRIR = new javax.swing.JMenuItem();
        GUARDAR = new javax.swing.JMenuItem();
        GUARDARC = new javax.swing.JMenuItem();
        SCANNER = new javax.swing.JMenuItem();
        SALIR = new javax.swing.JMenuItem();
        REPORTE = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        HELP = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[LFP]Practica1");

        jScrollPane2.setViewportView(txtArea);

        ARCHIVO.setText("Archivo");

        ABRIR.setText("Abrir");
        ABRIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABRIRActionPerformed(evt);
            }
        });
        ARCHIVO.add(ABRIR);

        GUARDAR.setText("Guardar");
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });
        ARCHIVO.add(GUARDAR);

        GUARDARC.setText("Guardar como..");
        GUARDARC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARCActionPerformed(evt);
            }
        });
        ARCHIVO.add(GUARDARC);

        SCANNER.setText("Analizar");
        SCANNER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCANNERActionPerformed(evt);
            }
        });
        ARCHIVO.add(SCANNER);

        SALIR.setText("Salir");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        ARCHIVO.add(SALIR);

        jMenuBar2.add(ARCHIVO);

        REPORTE.setText("Reportes");

        jMenuItem9.setText("Reporte Tokens");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        REPORTE.add(jMenuItem9);

        jMenuItem10.setText("Reporte Errores");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        REPORTE.add(jMenuItem10);

        jMenuBar2.add(REPORTE);

        HELP.setText("Ayuda");

        jMenuItem5.setText("Acerca de..");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        HELP.add(jMenuItem5);

        jMenuItem6.setText("Manual Usuario");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        HELP.add(jMenuItem6);

        jMenuItem7.setText("Manual Tecnico");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        HELP.add(jMenuItem7);

        jMenuBar2.add(HELP);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ABRIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABRIRActionPerformed
        // TODO add your handling code here:                
        if(seleccionar.showDialog(null,"Abrir") == JFileChooser.APPROVE_OPTION)
        {
            archivo = seleccionar.getSelectedFile();
            if(archivo.canRead())
            {
                if(archivo.getName().endsWith("psum"))
                {
                    String documento = Abrir(archivo);
                    txtArea.setText(documento);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Archivo No Compatible");                    
                }
            }
        }
    }//GEN-LAST:event_ABRIRActionPerformed

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
        // TODO add your handling code here:
        if(seleccionar.showDialog(null,"Guardar")== JFileChooser.APPROVE_OPTION)
        {
            archivo = seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("psum"))
            {
                String Documento = txtArea.getText();
                String mensaje = GuardarA(archivo,Documento);
                if(mensaje !=null)
                {
                    JOptionPane.showMessageDialog(null,mensaje);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Archivo no Compatible");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Guardar Documento de Texto");
            }
        }
    }//GEN-LAST:event_GUARDARActionPerformed

    private void GUARDARCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARCActionPerformed
        // TODO add your handling code here:
        if(seleccionar.showDialog(null,"Guardar Como")== JFileChooser.APPROVE_OPTION)
        {
            archivo = seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("psum"))
            {
                String Documento = txtArea.getText();
                String mensaje = Guardar(archivo,Documento);
                if(mensaje !=null)
                {
                    JOptionPane.showMessageDialog(null,mensaje);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Archivo no Compatible");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Guardar Documento de Texto");
            }
        }        
    }//GEN-LAST:event_GUARDARCActionPerformed

    private void SCANNERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCANNERActionPerformed
        // TODO add your handling code here:       
        Token datos = new Token();        
        datos.Scanner(txtArea.getText());
        //datos.generarListaA();
        //datos.generarListaB();
        datos.Graficotxt();        
        //Pintar();
    }//GEN-LAST:event_SCANNERActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"¿Desea salir de la aplicación?") == JOptionPane.OK_OPTION)
        {
         System.exit(0);   
        }
        else
        {
          
        }        
    }//GEN-LAST:event_SALIRActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"LFP PRACTICA\n Uzzi Libni Aarón Pineda Solórzano \n carné: 201403541");        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:        
    //    Automata reporte = new Automata();    
        Token reporte = new Token();
        reporte.ReporteTkn();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
  //      Automata reporte = new Automata();
        Token reporte = new Token();
        reporte.ReporteE();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
         try
     {
         File f = new File("E:/Lenguajes/Vacaciones/[LFP]Practica1_201403541/Manual de Usuario.pdf");
         Desktop.getDesktop().open(f);
     }
     catch(IOException e)
     {
         e.printStackTrace();;
     }
     catch(IllegalArgumentException e)
     {
         JOptionPane.showMessageDialog(null, "Archivo no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
         e.printStackTrace();
     }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        try
        {
            File f = new File("E:/Lenguajes/Vacaciones/[LFP]Practica1_201403541/Manual Técnico.pdf");
            Desktop.getDesktop().open(f);
        }
        catch(IOException e)
        {
            e.printStackTrace();;
        }
        catch(IllegalArgumentException e)
        {
            JOptionPane.showMessageDialog(null, "Archivo no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    public String Abrir(File archivo)
    {
        String documento="";
        try
        {
            entrada = new FileInputStream(archivo);
         int ascci;
         while((ascci = entrada.read()) !=-1)
         {
             char caracter =(char)ascci;
             documento +=caracter;
         }
        }catch(Exception e)
        {
            
        }  
        return documento;
    }
    
    public String Guardar(File archivo,String documento)
    {
        String mensaje = null;
        try
        {
         salida = new FileOutputStream(archivo);
         byte[] bytxt = documento.getBytes();
         salida.write(bytxt);
         mensaje="Archivo Guardado";
        }catch(Exception e)
        {
            
        }
        return mensaje;
    }
    
    public String GuardarA(File archivo,String documento)
    {
        String mensaje = null;
        try
        {
         salida = new FileOutputStream(archivo);
         byte[] bytxt = documento.getBytes();
         salida.write(bytxt);
         mensaje="Archivo Guardado";
        }catch(Exception e)
        {
            
        }
        return mensaje;
    }
    // ------------------------------------------------------------------ pintar letras --------------------------------------------------------------
    // palabra reservada -> azul, numero -> rojo, cadenas -> verde, llaves y corchetes -> morado, coma,punto y coma, dos puntos -> amarillo, otros -> negro
    
//    ListaTkn hola = new ListaTkn();
//    String comparar; int bindice;
//    public void Pintar()
//    {
//        comparar = txtArea.getText();
//        
//        hola.lexema.equals("pensum");
//        bindice = txtArea.getText().indexOf(hola.lexema);
//        pintarReservadas(bindice,comparar);
//                
//        hola.getLexema().equals("curso");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarReservadas(bindice,comparar);
//        
//        hola.getLexema().equals("codigo");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarReservadas(bindice,comparar);
//        
//        hola.getLexema().equals("nombre");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarReservadas(bindice,comparar);
//        
//        hola.getLexema().equals("creditos");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarReservadas(bindice,comparar);
//        
//        hola.getLexema().equals("prerrequisitos");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarReservadas(bindice,comparar);
//        
//        
//        hola.getLexema().equals("0");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarNumeros(bindice,comparar);
//        
//        hola.getLexema().equals("1");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarNumeros(bindice,comparar);
//        
//        hola.getLexema().equals("2");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarNumeros(bindice,comparar);
//        
//        hola.getLexema().equals("3");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarNumeros(bindice,comparar);
//        
//        hola.getLexema().equals("4");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarNumeros(bindice,comparar);
//        
//        hola.getLexema().equals("5");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarNumeros(bindice,comparar);
//                
//        hola.getLexema().equals("6");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarNumeros(bindice,comparar);
//        
//        hola.getLexema().equals("7");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarNumeros(bindice,comparar);
//        
//        hola.getLexema().equals("8");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarNumeros(bindice,comparar);
//        
//        hola.getLexema().equals("9");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarNumeros(bindice,comparar);
//        
//        hola.getTkn().equals("cadena");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarCadena(bindice,comparar);
//        
//        hola.getLexema().equals("{");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarLlaves(bindice,comparar);
//        
//        hola.getLexema().equals("}");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarLlaves(bindice,comparar);
//        
//        hola.getLexema().equals(",");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarComa(bindice,comparar);
//        
//        hola.getLexema().equals(";");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintarPComa(bindice,comparar);
//        
//        hola.getLexema().equals(":");
//        bindice = txtArea.getText().indexOf(hola.getLexema());
//        pintar2puntos(bindice,comparar);
//    }
//    
//    public void pintarReservadas(int pindice, String pcomparar)
//    {
//        bindice = pindice + hola.lexema.length() - 1;
//        
//        try        
//        {
//            txtArea.select(pindice, hola.lexema.length());            
//            txtArea.setSelectionColor(Color.blue);
//            txtArea.setSelectionStart(txtArea.getText().length());
//            
//            pcomparar = txtArea.getText().substring(pindice + hola.getLexema().length());
//            pindice = pcomparar.indexOf(hola.getLexema()) + pindice + hola.getLexema().length();
//            
//            if(pindice != bindice)
//            {
//                pintarReservadas(pindice,pcomparar);
//            }
//            else
//            {
//                bindice = 0;
//            }
//        }
//        catch(Exception e)
//        {
//            
//        }        
//    }
//    
//    public void pintarNumeros(int pindice, String pcomparar)
//    {                 
//        try        
//        {
//            bindice = pindice + hola.lexema.length() - 1;
//            
//            txtArea.select(pindice, hola.lexema.length());            
//            txtArea.setSelectionColor(Color.red);
//            txtArea.setSelectionStart(txtArea.getText().length());
//            
//            pcomparar = txtArea.getText().substring(pindice + hola.getLexema().length());
//            pindice = pcomparar.indexOf(hola.getLexema()) + pindice + hola.getLexema().length();
//            
//            if(pindice != bindice)
//            {
//                pintarNumeros(pindice,pcomparar);
//            }
//            else
//            {
//                bindice = 0;
//            }
//        }
//        catch(Exception e)
//        {
//            
//        }     
//    }
//    
//    public void pintarCadena(int pindice, String pcomparar)
//    {
//        try        
//        {
//            bindice = pindice + hola.lexema.length() - 1;
//            txtArea.select(pindice, hola.lexema.length());            
//            txtArea.setSelectionColor(Color.green);
//            txtArea.setSelectionStart(txtArea.getText().length());
//            
//            pcomparar = txtArea.getText().substring(pindice + hola.getLexema().length());
//            pindice = pcomparar.indexOf(hola.getLexema()) + pindice + hola.getLexema().length();
//            
//            if(pindice != bindice)
//            {
//                pintarCadena(pindice,pcomparar);
//            }
//            else
//            {
//                bindice = 0;
//            }
//        }
//        catch(Exception e)
//        {
//            
//        }  
//    }
//    
//    public void pintarLlaves(int pindice, String pcomparar)
//    {
//        try        
//        {
//            bindice = pindice + hola.lexema.length() - 1;
//            txtArea.select(pindice, hola.lexema.length());            
//            txtArea.setSelectionColor(Color.PINK);
//            txtArea.setSelectionStart(txtArea.getText().length());
//            
//            pcomparar = txtArea.getText().substring(pindice + hola.getLexema().length());
//            pindice = pcomparar.indexOf(hola.getLexema()) + pindice + hola.getLexema().length();
//            
//            if(pindice != bindice)
//            {
//                pintarLlaves(pindice,pcomparar);
//            }
//            else
//            {
//                bindice = 0;
//            }
//        }
//        catch(Exception e)
//        {
//            
//        }  
//    }
//    
//    public void pintarComa(int pindice, String pcomparar)
//    {
//        try        
//        {
//            bindice = pindice + hola.lexema.length() - 1;
//            
//            txtArea.select(pindice, hola.lexema.length());            
//            txtArea.setSelectionColor(Color.yellow);
//            txtArea.setSelectionStart(txtArea.getText().length());
//            
//            pcomparar = txtArea.getText().substring(pindice + hola.getLexema().length());
//            pindice = pcomparar.indexOf(hola.getLexema()) + pindice + hola.getLexema().length();
//            
//            if(pindice != bindice)
//            {
//                pintarComa(pindice,pcomparar);
//            }
//            else
//            {
//                bindice = 0;
//            }
//        }
//        catch(Exception e)
//        {
//            
//        }  
//    }
//    
//    public void pintarPComa(int pindice, String pcomparar)
//    {
//        try        
//        {
//            bindice = pindice + hola.lexema.length() - 1;
//            
//            txtArea.select(pindice, hola.lexema.length());            
//            txtArea.setSelectionColor(Color.yellow);
//            txtArea.setSelectionStart(txtArea.getText().length());
//            
//            pcomparar = txtArea.getText().substring(pindice + hola.getLexema().length());
//            pindice = pcomparar.indexOf(hola.getLexema()) + pindice + hola.getLexema().length();
//            
//            if(pindice != bindice)
//            {
//                pintarComa(pindice,pcomparar);
//            }
//            else
//            {
//                bindice = 0;
//            }
//        }
//        catch(Exception e)
//        {
//            
//        }  
//    }
//    
//    public void pintar2puntos(int pindice, String pcomparar)
//    {
//        try        
//        {
//            bindice = pindice + hola.lexema.length() - 1;
//            
//            txtArea.select(pindice, hola.lexema.length());            
//            txtArea.setSelectionColor(Color.yellow);
//            txtArea.setSelectionStart(txtArea.getText().length());
//            
//            pcomparar = txtArea.getText().substring(pindice + hola.getLexema().length());
//            pindice = pcomparar.indexOf(hola.getLexema()) + pindice + hola.getLexema().length();
//            
//            if(pindice != bindice)
//            {
//                pintarComa(pindice,pcomparar);
//            }
//            else
//            {
//                bindice = 0;
//            }
//        }
//        catch(Exception e)
//        {
//            
//        }  
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ABRIR;
    private javax.swing.JMenu ARCHIVO;
    private javax.swing.JMenuItem GUARDAR;
    private javax.swing.JMenuItem GUARDARC;
    private javax.swing.JMenu HELP;
    private javax.swing.JMenu REPORTE;
    private javax.swing.JMenuItem SALIR;
    private javax.swing.JMenuItem SCANNER;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane txtArea;
    // End of variables declaration//GEN-END:variables
}
